version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=nodeTask  
  app:
    build: .
    container_name: nodeTask-app
    ports:
      - "5000:5000" 
    depends_on:
      - mongo
    volumes:
      - .:/app

volumes:
  mongo-data: